# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/conf.py

formats: []

conda:
  environment: environment.yml

python:
  version: 3.7
  install:
    - method: setuptools
      path: stand_mapping

submodules:
  include: all
  recursive: true
